Add server, static JSON and instructions.
getyourguide/web-pairing-kit-associate pull request #1
Opened 2020-10-20 14:21 UTC by mauricio-gamboa

Please provide any feedback.

2020-10-20 15:50 UTC, xmajox requested changes
Added a couple of notes on the instructions, but overall seems good. we will collect feedback from the candidates and iterate as needed.

2020-10-20 15:50 UTC, xmajox commented on README.md
> +The excerice will have two parts.
```suggestion
The exercise will have two parts.
```

2020-10-20 15:50 UTC, xmajox commented on README.md
> +- The basic Frontend structure.
It is unclear to me what is the "basic" structure that you expect to be prepared. On the take-home requirements you only talk about building the API endpoint with the data source provided.

2020-10-21 06:49 UTC, Estlopacu commented on README.md
> +- We'd prefer to see actual CSS code (or a CSS in JS solution) rather than usage of a UI library.
```suggestion
- We'd prefer to see actual CSS code (or a CSS in JS solution) rather than the usage of a UI library like Bootstrap, Foundations, or Tailwind CSS.
```
I will add this recommendation as some candidates don't know what is a UI library. 😬

2020-10-21 09:00 UTC, mauricio-gamboa commented on README.md
> +- The basic Frontend structure.
I clarified this.

2020-10-21 10:14 UTC, xmajox approved these changes

2020-10-21 11:55 UTC, merged